name: "Setup Node.js Express and MySQL"
author: "<Sunwoo0110@gmail.com> && <jihooni0914@gmail.com>"
description: "A GitHub Action to setup node.js express and MySQL"
inputs:
   project-name: 
      description: "project name"
      required: true
      default: ''
   project-description:
      description: "project description"
      required: true
      default: ''
   repo-url:
      description: "project github repogitory url"
      required: true
      default: ''
runs:
   using: "docker"
   image: "Dockerfile"
   args:
      - ${{ inputs.project-name }}
      - ${{ inputs.project-description }}
      - ${{ inputs.repo-url }}
branding:
   icon: "navigation"
   color: "blue"
