name: "Setup Node.js Express and MySQL"
author: "<Sunwoo0110@gmail.com> && <jihooni0914@gmail.com>"
description: "A GitHub Action to setup Node.js Express and MySQL"
inputs:
   github-user-id: 
      description: "project name"
      required: true
      default: ''
   github-user-password: 
      description: "project name"
      required: true
      default: ''
   github-repo-url:
      description: "project github repogitory url"
      required: true
      default: ''
runs:
   using: "docker"
   image: "Dockerfile"
   args:
      - ${{ inputs.github-repo-url }}
      - ${{ inputs.github-user-id }}
      - ${{ inputs.github-user-email }}
      - ${{ inputs.github-user-password }}
      # - ${{ secrets.GITHUB-TOKEN }}
branding:
   icon: "navigation"
   color: "blue"
