name: "Setup Node.js Express and MySQL"
author: "<Sunwoo0110@gmail.com> && <jihooni0914@gmail.com>"
description: "A GitHub Action to setup Node.js Express and MySQL"
inputs:
   github-repo-url:
      description: "project github repository url"
      required: true
      default: ''
   github-user-id: 
      description: "user id"
      required: true
      default: ''
   gh-token: 
      description: "user PAT"
      required: true
      default: ''
runs:
   using: "docker"
   image: "Dockerfile"
   args:
      - ${{ inputs.github-repo-url }}
      - ${{ inputs.github-user-id }}
      - ${{ inputs.gh-token }}
branding:
   icon: "navigation"
   color: "blue"
