name: Git clone test2

on:
  workflow_dispatch:
    inputs:
      github-repo-url:
        description: "project github repogitory url"
        required: true
        default: ''
      github-user-id: 
        description: "project name"
        required: true
        default: ''
      github-user-password: 
        description: "project name"
        required: true
        default: ''


jobs:
   git_clone_test:
    runs-on: ubuntu-latest
    name: Git clone test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: node setup
        uses: actions/setup-node@v3
      - name: Setup
        with:
          github-repo-url: ${{ inputs.github-repo-url }}
          github-user-id: ${{ inputs.github-user-id }}
          github-user-email: "${{ inputs.github-user-id }}@gmail.com"
          github-user-password: ${{ github-user-password }}
        uses: ./ 
      - name: Test finish
        run: echo "test was good"
